apiVersion: v1
kind: Service
metadata:
  name: products-service-svc
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Exposes the service externally via a cloud load balancer
